= Filters and projections

After making a basic `MATCH` & `RETURN` Cypher query in xref:getting-started/querying.adoc[Querying], in this guide you'll add some filters and change the projection to only return some fields.

The resulting query will look like this:


```cypher
MATCH(m:Movie)
WHERE (m.title = "The Matrix" AND m.released < 2000)
RETURN m.title, m.tagline, m.released
```

[NOTE]
====
This query will return all movies with the name `"The Matrix"` released before `2000`. This query is based on the default example database in Neo4j, and will return the classic 1999 film **The Matrix**. 
====

== Filtering

When creating a `MATCH` clause, it is possible to add subclauses to it in a similar way to how you add the `RETURN` statement by using the method `.where`:

```javascript
const clause = new Cypher.Match(movieNode)
    .where()
    .return(movieNode);
```

The first step is to add the first condition of the filter:

```cypher
m.title = "The Matrix"
```

You'll use the function `Cypher.eq()`. This function takes 2 arguments and compares them with an **eq**uality operator (`=`):

* The property `title` of the `movieNode` variable:
+
```javascript
movieNode.property("title") 
```
* The value `"The Matrix`. It is possible to simply inject the string value into the query, however, it is good practice to use link:https://neo4j.com/docs/cypher-manual/current/syntax/parameters/[Parameters]. To add a parameter with Cypher Builder you'll need to use the `Cypher.Param` class:
+
```javascript
new Cypher.Param("The Matrix")
```
+
`Cypher.Param` will take care of replacing the value with a suitable placeholder.

Your match clause should now look like this:

```javascript
const clause = new Cypher.Match(movieNode)
    .where(Cypher.eq(movieNode.property("title"), new Cypher.Param("The Matrix")))
    .return(movieNode);
```

=== Cypher and params

By running the script again (`node main.js`), you should get the following Cypher:

```cypher
MATCH (this0:Movie)
WHERE this0.title = $param0
RETURN this0
```

That means `Movie` is now filtered by its title to a param, but the param itself is missing from the output.
To fix that, you need to modify the build process at the end of the script:

```javascript
const { cypher, params } = match.build();
console.log(cypher);
console.log(params);
```

After executing it, you'll get both, the Cypher query and its parameters:

```cypher
MATCH (this0:Movie)
WHERE this0.title = $param0
RETURN this0
```

```javascript
{ param0: 'The Matrix' }
```

=== `AND` filtering

The query still lacks the second filter, which needs to be concatenated with `AND`. Simply use the method `.and` after the `where` with a new `Cypher.eq` predicate:

```javascript
    .where(Cypher.eq(movieNode.property("title"), new Cypher.Param("The Matrix")))
    .and(Cypher.lt(movieNode.property("released"), new Cypher.Param(2000)))
```

This takes the same parameters as `.where`, and makes sure to properly concatenate the filters with `AND`. In this case, the function `Cypher.lt` will add the operator `<` (**l**ower **t**han). Same as before, the comparison happens between a property of `movieNode` and a param. This time the param is a number. Cypher Builder will take care of correctly passing it to the `params` object.

Running the script again:

```cypher
MATCH (this0:Movie)
WHERE (this0.title = $param0 AND this0.released < $param1)
RETURN this0
```

```javascript
{ param0: 'The Matrix', param1: 1999 }
```

This should look closer to the target query, note that now there are two parameters, each one correctly associated to the correct filter.

[NOTE]
====
Adding the `AND` operation automatically adds parenthesis to ensure operation precedence, this will be important when dealing with complex and nested filters 
====

== Projection

Usually, returning the full node is not desirable, for these cases, you can explicitly set a projection in the `RETURN` clause.

You can define multiple columns to return in the projection by passing them into the `.return` method. This method not only accepts Nodes, but any kind of variables, such as properties or params.

Let's update the return subclause:

```javascript
    .return(movieNode.property("title"), movieNode.property("tagline"), movieNode.property("year"));
```

The returned Cypher now should be:

```cypher
MATCH (this0:Movie)
WHERE (this0.title = $param0 AND this0.released < $param1)
RETURN this0.title, this0.tagline, this0.released
```

Success! You have now a query with filters and projections.

=== Reusing variables

Right now, this query is filtering and returning the properties `id` and `title` of the Movie nodes. However, the query relies on the name of these properties to remain the same. This, particularly with more complex queries, can lead to flaky queries, as it is hard to keep track of strings identifying values.

To fix this, you'll make a small adjustment to the script, so that both the filters and the projection use the same property variable:

```javascript
const titleProp = movieNode.property("title");
const yearProp = movieNode.property("released");
const taglineProp = movieNode.property("tagline");

const clause = new Cypher.Match(movieNode)
    .where(Cypher.eq(titleProp, new Cypher.Param("The Matrix")))
    .and(Cypher.lt(yearProp, new Cypher.Param(2000)))
    .return(titleProp, taglineProp, yearProp);
```

This change, not only ensures that different parts of the query are always in sync but also makes the clause itself shorter and easier to read.

[TIP]
====
Params can also be assigned to a variable and reused, this can be particularly useful when having multiple filters over the same parameter.
====

== Conclusion

After going through all the steps previously described, your script should now look similar to this:

```javascript
import Cypher from "@neo4j/cypher-builder";

const movieNode = new Cypher.Node({
    labels: ["Movie"],
});

const titleProp = movieNode.property("title");
const yearProp = movieNode.property("released");
const taglineProp = movieNode.property("tagline");

const clause = new Cypher.Match(movieNode)
    .where(Cypher.eq(titleProp, new Cypher.Param("The Matrix")))
    .and(Cypher.lt(yearProp, new Cypher.Param(2000)))
    .return(titleProp, taglineProp, yearProp);

const { cypher, params } = clause.build();
console.log(cypher);
console.log(params);
```

And its execution should show the following query:

```cypher
MATCH (this0:Movie)
WHERE (this0.title = $param0 AND this0.released < $param1)
RETURN this0.title, this0.tagline, this0.released
```

```javascript
{ param0: 'The Matrix', param1: 2000 }
```

With this, you already have the tools to make useful (albeit simple) queries and have also learnt how to deal with parameters. Feel free to try other filters operations (TODO: add link )

In the next tutorial, you'll add relationships and more complex filtering to this query.
