= Installation

In this guide, you'll set up a Node.js project with `@neo4j/cypher-builder`, after this, you'll be ready to start using Cypher Builder.

== Requirements

* link:https://nodejs.org/[Node.js] 16.0.0 or greater
* link:https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[npm]
* **[Optional]** A link:https://neo4j.com/cloud/platform/aura-graph-database/?ref=nav-get-started-cta[Neo4j] database to try Cypher queries.

== Installing Cypher Builder

In a folder of your choice, run the following command to create a Node.js project and a `package.json` file

```bash
npm init es6 -y
``` 

Note that these examples use ES6 modules, but CommonJS modules can be used as well.


Next, install link:https://www.npmjs.com/package/@neo4j/cypher-builder[`@neo4j/cypher-builder`] and add it to the dependencies list with the following command: 

```
npm install --save @neo4j/cypher-builder
```

Create a new file `main.js` with the following content:

```javascript
import Cypher from "@neo4j/cypher-builder";
```

Execute the script:

```bash
node main.js
```

At this moment, the script should not do anything, but if it doesn't show an error it means Cypher Builder has been correctly installed.

// TODO: add a "connect to the database" optional section
