[[migration]]
:description: This page describes how to migrate to version 2.x
= Migration to 2.0

This guide describes the changes required to migrate from Cypher Builder 1.x to 2.0, as well as some breaking changes that may affect projects using Cypher Builder.

The full, up to date changelog can be found link:https://github.com/neo4j/cypher-builder/blob/2.x/CHANGELOG.md[here].

== Patterns

xref:patterns.adoc[Patterns] have been reworked in version 1.x, and the old behavior have been removed in version 2.0.


=== Node shorthand removed from clauses

Clauses using Patterns no longer accept a `Cypher.Node` as a shorthand. An explicit pattern must be provided:


Before:
[source, javascript]
----
const movieNode = new Cypher.Node();

const matchQuery = new Cypher.Match(movieNode)
----


Now:
[source, javascript]
----
const movieNode = new Cypher.Node();

const matchQuery = new Cypher.Match(
    new Cypher.Pattern(movieNode)
);
----

This affects all clauses using patterns:

* `Cypher.Match`
* `Cypher.Create`
* `Cypher.Merge`

This also affects pattern comprehensions `Cypher.PatternComprehension`.


=== Patterns no longer create a variable by default

Creating a Pattern without options will no longer add variables to the generated Cypher:

[source, javascript]
----
const pattern = new Cypher.Pattern()
----

Before 

[source, cypher]
----
(this0)
----

Now

[source, cypher]
----
()
----

To add a variable, it must be passed when creating the pattern:

[source, javascript]
----
const movieNode = new Cypher.Node();
const pattern = new Cypher.Pattern(movieNode)
----


==== `.getVariables`

The method `.getVariables` has been removed from Patterns, as Patterns no longer create variables, `getVariables` is no longer useful.

=== Patterns configuration

The following methods to configure the resulting pattern have been removed from `Pattern`:

-   `.withoutLabels` 
-   `.withoutVariable`
-   `.withProperties`
-   `.withVariables`
-   `.withoutType`
-   `.withDirection`
-   `.withLength`

Instead, Patterns are now configured through objects in the constructor, as well as the `related` and `to` methods: 

Before
[source, javascript]
----
const a = new Cypher.Node({
    labels: ["Person", "Actor"],
});

const aProperties = {
    name: new Cypher.Param("Arthur"),
    surname: new Cypher.Param("Dent"),
};
const b = new Cypher.Node();
const rel = new Cypher.Relationship({
    type: "ACTED_IN",
});

new Cypher.Pattern(a)
    .withProperties({a: new Cypher.Param("Example")})
    .withoutVariable()
    .related(rel)
    .to(b)  
----

Now

[source, javascript]
----
const aProperties = {
    name: new Cypher.Param("Arthur"),
    surname: new Cypher.Param("Dent"),
};
const b = new Cypher.Node();
const rel = new Cypher.Relationship();


new Cypher.Pattern({ properties: aProperties, labels: ["Person", "Actor"] })
    .related(rel, { type: "ACTED_IN"})
    .to(b)
----


The generated Cypher:

[source, Cypher]
----
(:Person:Actor { name: $param0, surname: $param1 })-[this1:ACTED_IN]->(this2)
----

Note that labels and types are now defined in the Pattern, not in the `Node` and `Relationship` classes.

=== Assign to path variable

The method `assignToPath` has been removed in the following clauses:

- `Match`
- `Merge`
- `Create`

Instead, the method `assignTo` in `Patterns` must be used:

Before:

```js
const pathVariable = new Cypher.Cypher.PathVariable()
new Cypher.Match(pattern).assignToPath(pathVariable).return(pathVariable);
```

Now:

```js
const pathVariable = new Cypher.Cypher.PathVariable()
new Cypher.Match(pattern.assignTo(pathVariable)).return(pathVariable);
```

Generates the Cypher:

```cypher
MATCH p = ()-[]-()
RETURN p
```


== Node and Relationship variables

`Cypher.Node` and `Cypher.Relationship` no longer hold any data about labels, or types. Making them more similar to `Cypher.Variable`. To add labels or types, these need to be passed to the `Cypher.Pattern` instead of relying on `Cypher.Node` and `Cypher.Relationship`.

Before
[source, javascript]
----
const a = new Cypher.Node({
    labels: ["Person", "Actor"],
});
const b = new Cypher.Node();
const rel = new Cypher.Relationship({
    type: "ACTED_IN",
});

new Cypher.Pattern(a)
    .related(rel)
    .to(b)
----

Now

[source, javascript]
----
const a = new Cypher.Node();
const b = new Cypher.Node();
const rel = new Cypher.Relationship();


new Cypher.Pattern(a, { labels: ["Person", "Actor"] })
    .related(rel, { type: "ACTED_IN"})
    .to(b)
----

=== Path variables

The variables used for paths `Cypher.Path` and `Cypher.NamedPath` have been removed in favor of the more accurate names: `Cypher.PathVariable` and `Cypher.NamedPathVariable`  

== Renamed features

The following features where deprecated in favor of a different name with the same functionality. The deprecated features have been removed in version 2.0:

* `Cypher.concat` in favor of `Cypher.utils.concat`
* `pointDistance` in favor of `point.distance`
* `Merge.onCreate` in favor of `Merge.onCreateSet`
* `Call.innerWith` in favor of `Call.importWith`
* `cdc` namespace in favor of `db.cdc`
**   `db.cdc.current` 
**   `db.cdc.earliest` 
**   `db.cdc.query` 
*   `rTrim` and `lTrim` in favor of `rtrim` and `ltrim` respectively

== `.build()`

The options for `.build()` are now passed as a single object rather than parameters:

Before:
[source, javascript]
----
myClause.build(
    "another-this",
    { myParam: "hello"},
    {
        labelOperator: "&"
    }
);
----


Now:
[source, javascript]
----
myClause.build({
    prefix: "another-this",
    extraParams: {
        myParam: "hello",
    },
    labelOperator: "&",
});
----

All parameters are optional, and `build` can still be called without parameters.

== `With`

The method `.with` no longer adds new columns into the existing clause. It will always create a new `WITH` statement instead. The method `.addColumns` should be used instead to add extra columns. 

Before
[source, javascript]
----
const withQuery = new Cypher.With(node);
withQuery.with(node);
withQuery.with("*");
----

Now
[source, javascript]
----
const withQuery = new Cypher.With(node);
withQuery.with(node)
withQuery.addColumns("*");
----


The generated Cypher:

[source, cypher]
----
WITH this0
WITH *, this0
----

== `RawCypher`

`Cypher.RawCypher` has been removed in favor of `Cypher.Raw`.

=== Update callback parameter

`Cypher.Raw`` no longer exposes a `Cypher.Environment` variable. Instead, it provides a `CypherRawContext` instance with a `compile` method to compile nested elements in custom cypher.


Before
[source, typescript]
----
const releasedParam = new Cypher.Param(1999);
const rawCypher = new Cypher.Raw((env: Cypher.Environment) => {
    const releasedParamId = env.compile(releasedParam); // Gets the raw Cypher for the param

    const customCypher = `MATCH(n) WHERE n.title=$title_param AND n.released=${releasedParamId}`;

    return customCypher;
});
----

Now.
[source, typescript]
----
const releasedParam = new Cypher.Param(1999);
const rawCypher = new Cypher.Raw((ctx: Cypher.RawCypherContext) => {
    const releasedParamId = ctx.compile(releasedParam); // Gets the raw Cypher for the param

    const customCypher = `MATCH(n) WHERE n.title=$title_param AND n.released=${releasedParamId}`;

    return customCypher;
});
----

Note that the code itself has not changed, and just the type passed to `Cypher.Raw` callback has been changed from `Cypher.Environment` to `Cypher.RawCypherContext`.

=== Remove `utils.compileCypher`

The utility function `compileCypher` has been removed, in favor of using `CypherRawContext.compile`, which offers the same functionality.

== `PatternComprehension`

`PatternComprehension` no longer accept a node as an argument in the constructor, a Pattern must be passed instead:

Before
[source, javascript]
----
const node = new Cypher.Node();
const comprehension = new Cypher.PatternComprehension(node);
----

Now
[source, javascript]
----
const node = new Cypher.Node();
const comprehension = new Cypher.PatternComprehension(new Cypher.Pattern(node));
----

=== `.map`

`PatternComprehension` no longer accepts a second argument for the Map expression. The method `.map` must be used instead:

Before
[source, javascript]
----
const andExpr = Cypher.eq(node.property("released"), new Cypher.Param(1999));

const comprehension = new Cypher.PatternComprehension(new Cypher.Pattern(node), andExpr)
----

Now
[source, javascript]
----
const andExpr = Cypher.eq(node.property("released"), new Cypher.Param(1999));

const comprehension = new Cypher.PatternComprehension(new Cypher.Pattern(node)).map(andExpr);
----


== Other Breaking changes

These are breaking changes that do not require changes, but may affect the behaviour of projects updating to Cypher Builder 2.0.


=== Fix TypeScript typings for boolean operators

The typings for the following boolean operators have been fixed to better reflect the result of these functions when spread parameters are used:

*   `Cypher.and`
*   `Cypher.or`
*   `Cypher.xor`

The following:

[source, typescript]
----
const predicates: Cypher.Predicate[] = [];
const andPredicate = Cypher.and(...predicates);
----

Will now return the correct type `Cypher.Predicate | undefined`. This change means that additional checks may be needed when using boolean operators:

[source, typescript]
----
const predicates = [Cypher.true, Cypher.false];
const andPredicate = Cypher.and(...predicates); // type Cypher.Predicate | undefined
----

Passing parameters without spread will still return a defined type.


=== Literals escaping

`Cypher.Literal` will now escape strings if these contain invalid characters. This is to avoid code injection.


[source, javascript]
----
new Cypher.Literal(`Hello "World"`);
----

Would generate the following Cypher

Before: 
[source, cypher]
----
"Hello "World""
----

Now:
[source, cypher]
----
"Hello \"World\""
----

Note that `Cypher.Param` is still preferred over `Cypher.Literal` for dynamic values.
