[[migration]]
:description: This page describes how to migrate to version 3.x from version 2.
= Migration to Cypher Builder 3

This guide details all the changes needed to migrate from Cypher Builder version 2 to version 3.

[NOTE]
====
If you must support Neo4j 4, stay with Cypher Builder 2.x, otherwise, migrate to version 3.
====

== Compatibility changes

=== Moved to ES modules

Cypher Builder has been migrated to ES modules, and is no longer available as a CommonJS module.

=== Minimum node engine changed to 20.19.0

Node.js 16 is no longer supported.
Update Node.js to version 20.19.0 or above.

== Cypher 4 no longer supported

Cypher 4, and Neo4j 4 databases are no longer supported.
Cypher Builder 3 targets Cypher 5 and 25.

The following features are Cypher 4 only, and have been removed from Cypher Builder.

=== Removed functions deprecated in Cypher 5

The following functions are still supported in Cypher 5, but have been deprecated. These been removed from Cypher Builder: 

- `distance` in favor of `point.distance`
- `id` in favor of `elementId`

=== Removed support for patterns in size

No longer supported:
[source, javascript]
----
Cypher.size(new Cypher.Pattern(node));
----

[source, Cypher]
----
size((this0));
----

Instead, use `Cypher.Count`:

[source, javascript]
----
new Cypher.Count(new Cypher.Pattern(node));
----

[source, Cypher]
----
COUNT {
    (this0)
}
----

=== Removed `labelOperator`

Removed the option `labelOperator` from the `.build` method. The operator `&` is now the default operator when using multiple labels:


No longer supported:
[source, javascript]
----
const { cypher, params } = matchQuery.build({
    labelOperator: "&",
});
----


Before:
[source, Cypher]
----
MATCH (this1:Movie:Film)
----

After:
[source, Cypher]
----
MATCH (this1:Movie&Film)
----

The label operator `:` is no longer supported.


=== Removed `.importWith` from `Call`

Remove `.importWith` from `Call` clauses in favor of constructor parameters.

No longer supported:

[source, Javascript]
----
const clause = new Cypher.Call(nestedClause).importWith(movieNode, actorNode);
----

[source, Cypher]
----
CALL {
    WITH var0, var1
    // Nested clause
}
----

After:

[source, Javascript]
----
const clause = new Cypher.Call(nestedClause, [movieNode, actorNode]);
----

[source, Cypher]
----
CALL (var0, var1){
    // Nested clause
}
----

== Removed support for APOC

No APOC functions or procedures are supported in Cypher Builder 3.
The following are no longer available:

- `apoc.util.validate`
- `apoc.util.validatePredicate`
- `apoc.date.convertFormat`
- `apoc.cypher.runFirstColumnMany`
- `apoc.cypher.runFirstColumnSingle`

To use APOC methods, create a xref:how-to/customize-cypher.adoc#_custom_functions_and_procedures[custom function or procedure].
For example:

[source, Javascript]
----
function validate(
    predicate: Predicate,
    message: string,
    params: List | Literal | Map
): Cypher.VoidCypherProcedure {
    return new Cypher.VoidCypherProcedure(
        "apoc.util.validate", 
        [predicate,  new Literal(message), params]
    );
}
----

[source, Javascript]
----
function validatePredicate(predicate: Predicate, message: string): CypherFunction {
    return new CypherFunction("
        apoc.util.validatePredicate", 
        [predicate, new Literal(message), new Literal([0])]
    );
}
----

== API changes
The following are changes made to improve consistency across the Cypher Builder API.

=== ListComprehension

==== Removed the second parameter of the constructor
The second parameter of the `ListComprehension` constructor has been removed in favor of `.in`.

Before:
[source, javascript]
----
new Cypher.ListComprehension(variable, new Cypher.Literal([1, 2]));
----

After:
[source, javascript]
----
new Cypher.ListComprehension(variable).in(new Cypher.Literal([1, 2]));
----

In both cases, the same comprehension is generated:

```cypher
[var0 IN [1, 2]]
```

==== The `ListComprehension` method  `.in` no longer throws if called twice

The `ListComprehension` method `.in` no longer throws if called twice.
Instead, it overrides the expression.

Before, the following code will throw an error:
[source, javascript]
----
new Cypher.ListComprehension(variable).in(new Cypher.Literal([1, 2])).in(new Cypher.Literal([1]))
----

After, it will generate the following Cypher:

[source, cypher]
----
[var0 IN [1]]
----

Note that the same Cypher is generated if you omit the first `.in`:

[source, javascript]
----
new Cypher.ListComprehension(variable).in(new Cypher.Literal([1]))
----


=== Foreach

==== Removed extra parameters in the `Cypher.Foreach` constructor

The extra parameters in the `Cypher.Foreach` constructor have been removed in favor of the methods `in` and `do`.

For example, to create the following Cypher:

[source, Cypher]
----
FOREACH (var0 IN [1, 2, 3] |
        CREATE (this1:Movie)
        SET
            this1.id = var0
    )
----

Before:

[source, javascript]
----
const list = new Cypher.Literal([1, 2, 3]);
const variable = new Cypher.Variable();

const movieNode = new Cypher.Node();
const createMovie = new Cypher.Create(new Cypher.Pattern(movieNode, { labels: ["Movie"] })).set([
    movieNode.property("id"),
    variable,
]);

const foreachClause = new Cypher.Foreach(variable, list, createMovie);
----

After:

[source, javascript]
----
const list = new Cypher.Literal([1, 2, 3]);
const variable = new Cypher.Variable();

const movieNode = new Cypher.Node();
const createMovie = new Cypher.Create(new Cypher.Pattern(movieNode, { labels: ["Movie"] })).set([
    movieNode.property("id"),
    variable,
]);

const foreachClause = new Cypher.Foreach(variable).in(list).do(createMovie);
----

== Other breaking changes

=== Removed method `.children` from concat clauses

[source, Javascript]
----
const query = Cypher.utils.concat(clause1, clause2);
query.children; // No longer supported
----

=== Removed type `Operation`

The type `Cypher.Operation` is no longer available, use `Cypher.Expr` instead:

Before:
[source, javascript]
----
const myOperation: Cypher.Operation = Cypher.and()
----

After:
[source, javascript]
----
const myOperation: Cypher.Expr = Cypher.and()
----

== Other changes

=== Changed Cypher formatting

Generated Cypher has been changed to better follow the best practices recommended by the link:https://neo4j.com/docs/cypher-manual/current/styleguide/[Cypher Styleguide].

For example:

Before:
[source, Cypher]
----
CALL {
    CREATE (this0:Movie)
    SET
        this0.id = "The Matrix"
    RETURN this0
}
RETURN this0
----

After:
[source, Cypher]
----
CALL {
  CREATE (this0:Movie)
  SET this0.id = 'The Matrix'
  RETURN this0
}
RETURN this0
----

This doesn't have any impact on the behavior itself, and should not cause any breaking changes.
It may however affect projects that modify or test the exact output of the Cypher generated with Cypher Builder.
