/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [http://neo4j.com]
 */

import { CypherASTNode } from "../../CypherASTNode";
import type { CypherEnvironment } from "../../Environment";
import type { Expr } from "../../types";

const ConcatOperator = "||";

/**
 * The concatenation operator (`||`) generated by {@link concat}
 * @group Operators
 * @category String
 */
export class ConcatOp extends CypherASTNode {
    private readonly exprs: Expr[];

    /** @internal */
    constructor(exprs: Expr[]) {
        super();
        this.exprs = exprs;
    }

    /**
     * @internal
     */
    public getCypher(env: CypherEnvironment): string {
        const exprs = this.exprs.map((e) => e.getCypher(env));

        const operatorStr = ` ${ConcatOperator} `;
        return `(${exprs.join(operatorStr)})`;
    }
}

/** Concat (||) operator. This operator may be used for concatenating strings. For concatenating Cypher builder clauses use `utils.concat`
 * @see {@link https://neo4j.com/docs/cypher-manual/current/syntax/operators/#syntax-concatenating-two-strings-doublebar | Cypher Documentation}
 * @group Operators
 * @category String
 * @since Neo4j 5.19
 */
export function concat(leftExpr: Expr, rightExpr: Expr): ConcatOp;
export function concat(...exprs: Expr[]): ConcatOp;
export function concat(...exprs: Expr[]): ConcatOp {
    return new ConcatOp(exprs);
}
